<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px" />

# Numpy Ladder Challenge - Notebook 1

_Author:_ Tim Book

# Climb the Ladder!
Our class moves quickly! Sometimes, it feels like we make leaps in logic that are a bit too big. In this ladder challenge, we'll learn some core math concepts, some linear algebra, and the `numpy` library. Problems in this notebook start out easy and progressively get harder, so that the next rung of the Python ladder is always within reach.

Additionally, since not all of the topics discussed in this ladder challenge are explicitly taught in our course, these problems come with many more hints, tips, suggestions, and even sometimes a mini-lesson. You are encouraged to Google frequently throughout the lesson. In many ways, this ladder is meant to be a challenge as well as educational in its own right.

# One Rule: NO LOOPS
`numpy` takes advantage of **vectorized calculations**. A vectorized calculation is where one calculation occurs throughout the entire vector. For example, for a vector `v`, if we want a vector `w` that is all the elements of `v` plus one:

```
# GOOD! This is vectorized!
w = v + 1

# BAD! This is hard to read and extremely inefficient!
for i in range(len(v)):
    w[i] = v[i] + 1
```

**None of the exercises in this notebook require a loop. If you use a loop to solve any of these problems, you are solving the problem incorrectly.**

# Section I - Vectors and some vector math

0) Import the `numpy` library, aliasing it to be `np`

In [40]:
import numpy as np

1) Make the following vector defined as `v`:
    $$\mathbf{v} = (3, -1, 5, 2, -7)$$

In [41]:
v = np.array([3, -1, 5, 2, -7])
print(v)

[ 3 -1  5  2 -7]


2) Make the following vector defined as `w` using `np.arange()`:
    $$\mathbf{w} = (2, 3, 4, 5, 6)$$

In [42]:
w = np.arange(2, 7)
print(w)

[2 3 4 5 6]


3) Find $\mathbf{v} + \mathbf{w}$.

In [43]:
v + w

array([ 5,  2,  9,  7, -1])

4) What's the element-wise product of $\mathbf{v}$ and $\mathbf{w}$?

In [44]:
v * w

array([  6,  -3,  20,  10, -42])

5) Triple every element of `v`. (Do not reassign.)

In [45]:
v * 3

array([  9,  -3,  15,   6, -21])

6) Double every element of `w` and then subtract 2 from every element. (Do not reassign.)

In [46]:
print(w)
(w * 2) - 2

[2 3 4 5 6]


array([ 2,  4,  6,  8, 10])

7) Index `v` to show me the number `-1`.

In [47]:
print(v)
v[1]

[ 3 -1  5  2 -7]


-1

8) Index `v` to show me everything except the 0th element.

In [48]:
print(v)
v[1:]

[ 3 -1  5  2 -7]


array([-1,  5,  2, -7])

9) Index `v` to show me the elements at index 4, 2, and 3 (in that order).

In [49]:
print(v)
v[[4, 2, 3]]

[ 3 -1  5  2 -7]


array([-7,  5,  2])

10) Reassign the element of `v` at index 2 to be 6.

In [50]:
print(v)
v[2] = 6
print(v)

[ 3 -1  5  2 -7]
[ 3 -1  6  2 -7]


### Mini-Lesson: Filtering
Inequalities are also vectorized in `numpy`. For example:

```
v > 2
==> array([ True, False,  True, False, False])
```

You can also **filter** a vector using booleans, like follows:

```
v[[True, False,  True, False, False]]
==> array([3, 6])
```

The vector keeps anything `True`, and drops anything `False`.  It then follows you can filter a vector using the vector itself, like this:

```
v[v > 2]
==> array([3, 6])
```

11) Show me all of the positive elements of `v`.

In [51]:
print(v)
v[v > 0]

[ 3 -1  6  2 -7]


array([3, 6, 2])

12) How many elements of `v` are positive? (Use `numpy` to answer this question, do not count manually).

In [52]:
print(v[v > 0])
print(len(v[v > 0]))
print(np.count_nonzero(v > 0))
np.sum(v > 0)

[3 6 2]
3
3


3

13) Show me all of the even elements of `w`.

In [53]:
print(w)
w_even = w[w % 2 == 0]
print(w_even[w_even > 0])
w_mask = np.logical_and([w % 2 == 0], [w > 0])
w[w_mask[0]]




[2 3 4 5 6]
[2 4 6]


array([2, 4, 6])

14) Show me all of the positive even elements of `v`.

In [54]:
print(v)
v_even = v[v % 2 == 0]
print(v_even[v_even > 0])
v_mask = np.logical_and([v % 2 == 0], [v > 0])
v[v_mask[0]]

[ 3 -1  6  2 -7]
[6 2]


array([6, 2])

15) Redefine all the negative elements of `v` to be zero. This is a common sort of operation to do for real-world data! 

_Hint:_ Using `np.where` is one of two easy ways to do this. The other is the reassign the vector while filtering.  Do both ways if you can! 

In [55]:
print(f"original v  = {v}")
v_zeros = np.where(v < 0, 0, v)
print(f"v_zeros     = {v_zeros}")
v[v < 0] = 0
print(f"reasigned v = {v}")

original v  = [ 3 -1  6  2 -7]
v_zeros     = [3 0 6 2 0]
reasigned v = [3 0 6 2 0]


16) Create a new vector that's `"EVEN"` if the corresponding element of `w` is even, and `"ODD"` otherwise.

In [56]:
print(w)
w_even = w[np.where(w % 2 == 0, True, False)]
print(w_even)
w_odd = w[np.where(w % 2 == 1, True, False)]
print(w_odd)


[2 3 4 5 6]
[2 4 6]
[3 5]


# Section II - Statistics and vector operations

### Emails
For the next few problems, consider the following vector which represents the number of emails my inbox gets over the span of 20 days.

In [57]:
emails = np.array([25, 2, 45, 6, -2, 4, 4, 10, 6, -3, 16, 39, 19, 0, 1, -11, 25, 2, 7, 17])

17) A few data points were accidentally recorded as negative when they should be positive. Reassign `emails` to fix these records.

In [58]:
print(emails)
emails = np.where(emails < 0, emails * -1, emails)
print(emails)

[ 25   2  45   6  -2   4   4  10   6  -3  16  39  19   0   1 -11  25   2
   7  17]
[25  2 45  6  2  4  4 10  6  3 16 39 19  0  1 11 25  2  7 17]


18) What is the mean number of emails I get per day?

In [59]:
np.mean(emails)

12.2

19) Among days where I get more than 15 emails, what is the mean number of emails I get?

In [60]:
print(emails[emails > 15])
round(np.mean(emails[emails > 15]), 2)

[25 45 16 39 19 25 17]


26.57

20) What proportion of days do I receive more than 20 emails?

In [61]:
np.mean(emails > 20)

0.2

### Probabilities
For the next few problems, consider the following vector of probabilities:

In [62]:
p = np.array([0.69, 0.38, 0.68, 0.23, 0.26, 0.59, 0.94, 0.77, 0.85, 0.89])

21) The _odds_ of an event occuring is defined as the probability an even occuring divided by the probability that it doesn't. That is:

$$\text{odds} = \frac{p}{1 - p}$$

Compute the odds of all of the probabilities in `p`. Remember, no loops!

In [63]:
p / (1 - p)

array([ 2.22580645,  0.61290323,  2.125     ,  0.2987013 ,  0.35135135,
        1.43902439, 15.66666667,  3.34782609,  5.66666667,  8.09090909])

22) Later in the course, we'll need to compute **log odds** of probabilities. That is,

$$\log\frac{p}{1 - p}$$

where $\log$ is the natural logarithm. Compute the log odds for all the probabilities in `p`.

In [64]:
np.log(p/(1-p))

array([ 0.8001193 , -0.48954823,  0.7537718 , -1.20831121, -1.04596856,
        0.36396538,  2.75153531,  1.20831121,  1.73460106,  2.0907411 ])

23) Create a variable `predictions` that is `1` if the value of `p` is greater than `0.5` and `0` otherwise.

In [65]:
predictions = np.where(p > .5, 1, 0)
print(predictions)

[1 0 1 0 0 1 1 1 1 1]


24) What proportion of our predictions are `1`?

In [66]:
np.mean(predictions)

0.7

25) Below, the vector `y` represents the true outcomes of the event occuring. In this case, `p` was actually our predicted probabilities of an event occuring. What proportion of the time were our predictions correct? More simply put, what proportion of the time do our `predictions` and `y` vectors match up? Later in the course, this will be known as our **prediction accuracy**.

In [67]:
print(predictions)
y = np.array([0, 0, 1, 0, 0, 0, 1, 1, 1, 1])
print(y)
np.mean(np.where(predictions == y, True, False))

[1 0 1 0 0 1 1 1 1 1]
[0 0 1 0 0 0 1 1 1 1]


0.8

26) Sometimes, we'll want the **log loss** in a problem like this. While we'll normally let this get calculated for us automatically, it's good to do it once. Here's the formula:

$$\text{LogLoss} = \sum\left[-y_i \log p_i - (1 - y_i) \log (1 - p_i)\right]$$

### Mini-Lesson: How to read formulas like this!
We will encounter intimidating formulas like this countless times throughout our course. Their bark is worse than their bite, I promise. Let's dissect how to read them:

* **Subscripts** - The symbol $y_i$ represents the $i$th element of the vector $y$. In this case, that is represented by our numpy array `y`. Similarly, $p_i$ is the $i$th element of $p$, which we have as `p`.
* **Calculation** - For each $i$, we will calculate $-y_i \log p_i - (1 - y_i) \log (1 - p_i)$. So, for our 10-length vectors, we will have a resulting 10-length vector.
* **Summation** - The symbol $\Sigma$ is the Greek letter "sigma" - which is the Greek version of "s". In this case, "s" stands for "sum". It implies we'll be summing together all of our 10 calculations.

Let's solve problem 26 in two easy steps:

26a) Compute $-y_i \log p_i - (1 - y_i) \log (1 - p_i)$ for each $i$. Call this result `loglik_i`.

In [68]:
loglik_i = (-y * np.log(p)) - ((1 - y) * np.log(1 - p))
loglik_i

array([1.17118298, 0.4780358 , 0.38566248, 0.26136476, 0.30110509,
       0.89159812, 0.0618754 , 0.26136476, 0.16251893, 0.11653382])

26b) Sum the previous result to get our answer!

In [69]:
log_loss = sum(loglik_i)
print(log_loss)

4.091242153066264
