<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px" />

# Numpy Ladder Challenge - Notebook 3

_Author:_ Tim Book

# Climb the Ladder!
Our class moves quickly! Sometimes, it feels like we make leaps in logic that are a bit too big. In this ladder challenge, we'll learn some core math concepts, some linear algebra, and the `numpy` library. Problems in this notebook start out easy and progressively get harder, so that the next rung of the Python ladder is always within reach.

Additionally, since not all of the topics discussed in this ladder challenge are explicitly taught in our course, these problems come with many more hints, tips, suggestions, and even sometimes a mini-lesson. You are encouraged to Google frequently throughout the lesson. In many ways, this ladder is meant to be a challenge as well as educational in its own right.

**Remember our one rule: NO LOOPS! None of the exercises in this notebook require a loop. If you use a loop to solve any of these problems, you are solving the problem incorrectly.**

0) Import numpy in the usual way

In [1]:
import numpy as np

# Section V: All the Matrix Algebra in the World
This final section is going to be a little bit different. We are aware than many students come to DSI from a wide variety of backgrounds, and many students have very little experience with linear algebra. However, data science is an intensely mathematical subject, and most of that math is linear algebra.

This section is going to teach you some of the linear algebra topics we need while also giving you hands-on examples of how it might be carried out in raw `numpy`.

## Part 1: Vector Norms
While vectors are often drawn as arrows, really they are simply points on a coordinate plane. They can be denoted many ways using mathematical notation, but which you use depends on what field of study you are in, or whichever is most convenient to your situation. That is, the following are all the same vector:

$$
\mathbf{v} = (3, 4) = 
\begin{bmatrix}
3 \\ 4
\end{bmatrix} =
\begin{bmatrix}
3 & 4
\end{bmatrix}
$$

Where the middle one (the "column vector") is often the most convenient when doing matrix algebra, so that is what we will use.

The **norm** of a vector is the distance from that vector to the **origin** (that is, $(0, 0)$). It is denoted and computed as follows:

$$
\|\mathbf{v}\| =
    \sqrt{\mathbf{v}^T\mathbf{v}} =
    \sqrt{\mathbf{v} \cdot \mathbf{v}} =
    \sqrt{\sum v_i^2}
$$

For the next few problems, we'll use the following vectors:

In [2]:
v = np.load("data/v.npy")
w = np.load("data/w.npy")

68) Compute the vector norm of the vector $\mathbf{v}$ using the matrix algebra we've learned so far in `numpy`.

In [8]:
np.round(v)

array([-1.,  1.,  0.,  1.,  0.,  1., -0.,  1., -1., -0., -1., -0.,  0.,
        0., -0., -2., -1., -0.,  0., -1., -1., -2.,  0., -0., -0.,  2.,
       -1., -0.,  1.,  1., -1., -1., -1.,  0.,  0.,  0.,  0.,  0., -3.,
       -0.,  1.,  2.,  1., -2., -1.,  1., -1.,  1.,  1.,  1.,  0., -1.,
        0.,  1., -1., -1., -1., -0., -1.,  1.,  2.,  0., -3., -1., -0.,
       -0., -0.,  2.,  0., -0., -1., -0., -1.,  1., -1.,  1.,  1.,  1.,
       -0., -0., -0., -2.,  1.,  1.,  1.,  1.,  0., -0., -0., -1.,  1.,
       -2.,  1., -1.,  2.,  2., -0.,  0., -1.,  0.,  1.,  1.,  0., -1.,
        1., -1.,  1., -1.,  0., -1.,  1., -0.,  1., -1.,  0., -1.,  0.,
       -0., -1.,  0.,  1.,  1., -2., -0., -2., -2.,  1., -1.,  0.,  0.,
        0.,  0., -1.,  0., -2.,  1.,  1.,  0., -1., -0., -1.,  0., -1.,
        2., -1.,  1., -0., -1., -1., -0., -2.,  1., -0.,  1., -0.,  1.,
       -2., -0., -1., -0.,  1.,  0., -1., -0., -1.,  0., -1., -0., -0.,
       -2.,  0., -1., -1.,  1.,  2.,  1., -1., -2.,  1.,  1.,  0

In [4]:
np.sqrt(np.dot(v, v))

32.42912470151627

69) Compute the vector norm of the vector $\mathbf{v}$ using a built-in `numpy` function.

* _Hint:_ `np.linalg.something()`

In [9]:
np.linalg.norm(v)

32.42912470151627

**The distance between two vectors** is given by the norm of their difference. That is,

$$d(\mathbf{v}, \mathbf{w}) = \|\mathbf{v} - \mathbf{w}\|$$

70) Compute the distance between $\mathbf{v}$ and $\mathbf{w}$

In [16]:
np.linalg.norm(v) - np.linalg.norm(w)

1.1451124873076992

There are actually many kinds of distances. The one I've shown you so far is the most common, and it goes by many names, usually **Euclidean distance** or **$\mathcal{l}_2$ distance**. There is also an **$\mathcal{l}_1$ distance**, sometimes called **Taxi cab distance** or **Manhattan distance**:

$$\|\mathbf{v}\|_1 = \sum |v_i|$$

Can you figure out why it gets these names?

71) Compute the Manhattan distance between $\mathbf{v}$ and $\mathbf{w}$.

* _Hint:_ You can actually use the same function from numbers 69 and 70!

In [17]:
np.linalg.norm(v, ord=1) - np.linalg.norm(w, ord=1)

8.405722350155315

## Part 2: Linear Regression
The first type of machine learning model (aka "statistical model") we'll learn in our course is the **ordinary least squares linear regression model** (usually just **linear regression** or **OLS** for short).

In linear regression, we believe that our (quantitative) $y$ variable depends on some linear relationship of our $x$ variables. That is, if we have 3 $x$s, for observation $i$,

$$y_i = \beta_0 + \beta_1x_{1i} + \beta_2x_{2i} + \beta_3x_{3i}$$

We often like to incorporate _all_ of our data into this equation by writing this formula in matrix notation, which is actually much more concise:

$$\mathbf{y} = \mathbf{X}\beta$$

Where

$$
\begin{align}
\mathbf{y} = 
\begin{bmatrix}
y_1 \\ y_2 \\ \vdots \\ y_n
\end{bmatrix}
& \text{, }
\mathbf{\beta} = 
\begin{bmatrix}
\beta_0 \\ \beta_1 \\ \vdots \\ \beta_p
\end{bmatrix}
\end{align}
$$

and the **data matrix** (or **design matrix**) is:

$$
\mathbf{X} =
\begin{bmatrix}
1 & x_{11} & x_{12} & \cdots & x_{1p} \\
1 & x_{21} & x_{22} & \cdots & x_{2p} \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
1 & x_{n1} & x_{n2} & \cdots & x_{np} \\
\end{bmatrix}
$$

72) Using a paper and pencil, multiply out $\mathbf{y} = \mathbf{X}\beta$ as denoted above. Verify to yourself that this makes sense, and that it matches the first equation above (for $p = 3$). Really, take the time to do this! Being comfortable with equations like these is an import concept in our course.

73) We load some data below. However, it doesn't include that column of ones that corresponds to the $y$-intercept ($\beta_0$). Create a matrix $\mathbf{X}$ by adding the column of ones.

* _Hint:_ Use `np.hstack()`

In [93]:
X = np.load("data/X.npy")
y = np.load("data/y.npy")

In [94]:
X.shape

(1000, 7)

In [95]:
y.shape

(1000,)

In [107]:
X[0:5]

array([[ 0.6087,  1.6917, -0.6201,  0.7833, -0.2786,  0.6323,  0.4737],
       [ 0.6453, -0.6079,  0.0247, -0.1813,  2.0312, -0.2234, -0.6828],
       [ 0.9917,  0.4737,  0.1412,  0.9315,  0.1912, -1.2856,  0.859 ],
       [-0.2463,  1.269 ,  2.0164, -0.3703, -0.0937,  1.4895, -0.9341],
       [-0.4064, -0.2413,  0.0439,  1.0217, -1.8868,  0.584 , -0.1651]])

In [106]:
y[0:5]

array([ 43.83293388, -57.53377397,   0.39201501,  13.26679992,
        65.94408029])

In [121]:
X = np.append(
    np.ones([len(X),1])
    , X, axis=1)

74) What are the dimensions of $\mathbf{X}$? How many observations are in this data set, and how many variables? What should be the size of $\beta$?

In [124]:
X.shape
# X has 1000 observations with 7 features per observation, plus the bias

(1000, 8)

The goal of OLS is to estimate $\beta$. When we estimate a value, we like to put a "hat" on it. The estimate of $\beta$ is then $\hat{\beta}$, and our predictions for our observations are $\hat{\mathbf{y}}$. OLS is one of the rare opportunities where we can computer $\hat{\beta}$ directly. It has the following formula:

$$\hat{\beta} = (\mathbf{X}^T\mathbf{X})^{-1}\mathbf{X}^T\mathbf{y}$$

75) Compute $\hat{\beta}$. Save it as `beta_hat`.

In [156]:
beta_hat = np.dot(
    np.linalg.inv((np.dot(np.transpose(X), X))),
    np.dot(np.transpose(X),y)
    )

76) Compute our predictions. That is, $\mathbf{\hat{y}} = \mathbf{X}\hat{\beta}$. Save this as `y_hat`.

In [157]:
y_hat = np.dot(X, beta_hat)

A variant on OLS is called **ridge regression**, where, for some number $\lambda$, we instead compute

$$\hat{\beta}^\text{ridge} = (\mathbf{X}^T\mathbf{X} + \lambda I)^{-1}\mathbf{X}^Ty$$

where $I$ is the approprate identity matrix.

77) Compute $\hat{\beta}^\text{ridge}$ for $\lambda = 50$. Call this `beta_hat_ridge`.

In [158]:
I = np.dot(50, np.eye(X.shape[1]))
I.shape

(8, 8)

In [159]:
beta_hat_ridge = np.dot(
    np.linalg.inv(
        np.add(np.dot(np.transpose(X), X), I)
        ),

np.dot(np.transpose(X), y)

)

78) Compute the predictions for this model, $\hat{\mathbf{y}}^\text{ridge}$. Call this `y_hat_ridge`.

In [160]:
y_hat_ridge = np.dot(X, beta_hat_ridge)
y_hat_ridge

array([ 1.90886572e+01, -1.15575922e+01,  5.27272501e+00,  6.00323339e+00,
        3.53689213e+01,  1.84535291e+00,  6.44144700e+00,  2.69719410e+01,
       -1.26838469e+00,  3.34734896e+01,  3.02627459e+01, -6.48170449e+00,
        2.63909548e+01,  5.37296048e+00,  1.17338578e+01,  1.80674248e+01,
        2.09614238e+01,  1.45624359e+01, -1.42091103e+01,  4.24095694e+01,
       -9.35467070e+00, -1.87142737e+01,  3.46362470e+00, -1.45895898e+01,
        1.74557721e+01,  3.89491708e+00,  2.02943826e+01,  1.27497023e+00,
        1.21984733e+01,  2.54631872e+01,  6.68123638e+00, -2.69097343e+00,
       -7.29380199e+00,  9.68028788e+00,  2.04954404e+01,  1.21060179e+01,
        7.91342597e-01,  1.09506964e+01,  6.50083711e+00,  2.01395024e+00,
       -2.76965574e+01,  1.22300800e+01,  1.02650908e+01,  1.74520817e+01,
       -7.16803707e+00,  1.32416560e+01,  1.71069189e+01,  2.93213693e+01,
        8.85669165e+00,  2.13427433e+01, -5.07082518e+00, -7.35465978e+00,
        1.02523820e+01,  

79) Compute $\|\hat{\beta}\|$ and $\|\hat{\beta}^\text{ridge}\|$. Which is smaller?

In [161]:
np.linalg.norm(y_hat)

501.8519346055608

In [162]:
np.linalg.norm(y_hat_ridge) # smaller

476.57049193192404

## Part 3: MSE

Computing $\hat{\beta}$ involves minimizing the MSE. We can now also write the MSE in terms of matrix algebra:

$$
\begin{align}
MSE &= \frac{1}{n} \sum (y_i - \hat{y}_i)^2 \\
    &= \frac{1}{n} (\mathbf{y} - \hat{\mathbf{y}})^T(\mathbf{y} - \hat{\mathbf{y}}) \\
    &= \frac{1}{n} \|\mathbf{y} - \hat{\mathbf{y}}\|^2
\end{align}
$$

80) Take a paper and pencil and verify that all three of these things are equivalent.

81) Compute the $MSE$ using the first equation. (You already did this in an earlier exercise).

In [171]:
(np.round((y - y_hat))**2).mean()

392.637

82) Compute the $MSE$ using the second equation. That is, using matrix multiplication.

In [174]:
1/len(y) * np.dot(np.transpose((y - y_hat)), np.subtract(y, y_hat))

392.62066523979547

83) Compute the $MSE$ using the third equation. That is, using `np.linalg.norm()`.

In [178]:
1/len(y) * np.linalg.norm(np.subtract(y, y_hat))**2

392.62066523979547

84) Write a function that takes in `y` and `y_hat` and computes the $MSE$.

In [179]:
def MSE(y, y_hat):
    return (np.round((y - y_hat))**2).mean()

85) Compute the $MSE$ for both the OLS and ridge regression predictions in the previous part. Which model has a higher MSE?

In [180]:
MSE(y, y_hat)

392.637

In [181]:
MSE(y, y_hat_ridge) # ridge has the higher MSE

393.031

## **Bonus: Not required** Part 4: Singular Value Decomposition
There are many kinds of **matrix decomposition**. Matrix decomposition involves taking a matrix, and breaking it into the product of other matrices that are easier to work with. Any real-valued matrix $M$ can be broken up into its **singular value decomposition**:

$$M = USV^T$$

where:

* $U$ and $V$ are **orthonormal matrices** (more on this soon). The columns of $U$ and $V$ are referred to as the **left** and **right singular vectors**, respectively.
* $S$ is a **diagonal matrix**, where the elements of the diagonal are the **singular values** in descending order.

That is, $S$ looks like:

$$
S = 
\begin{bmatrix}
\sigma_1 & 0 & 0 & \cdots & 0 \\
0 & \sigma_2 & 0 & \cdots & 0 \\
0 & 0 & \sigma_3 & \cdots & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & 0 & 0 & \cdots & \sigma_m
\end{bmatrix}
$$

There are _**A LOT**_ of confusing definitions here, so let's dive into them individually.

Below, we read in a matrix of pixel values that make up a pleasant image. We can use `plt.imshow()` to plot a matrix visually.

In [ ]:
import matplotlib.pyplot as plt
doge = np.load("data/doge.npy")[:, 200:740]
print(doge.shape)
plt.imshow(doge, cmap="gray");

86) Use the `np.linalg.svd()` function to decompose our `doge` matrix. Please skim the documentation of this function! Note that it returns $V^T$, and not $V$. It also returns a vector of the singular values, not the full $S$ matrix.

The **singular values** are non-negative numbers in descending order. An easy way to think about them is that they represent how much _information_ we can represent in our matrix using a linear transformation. In the special case of a square matrix $M$, the singular values are also **eigenvalues**. (Similarly, the left singular vectors are the corresponding **eigenvectors**).

We recognize this still probably doesn't make a whole lot of sense. By the end of this exercise, we can interpret them visually, and hopefully that will clear things up.

87) Use our vector of singular values to make an `smat` matrix corresponding to $S$ as shown above.

* _Hint:_ Use `np.diag()`.

The matrices $U$ and $V$ are **orthonormal**. This means they have the following properties:

$$UU^T = UU^{-1} = I$$
$$VV^T = VV^{-1} = I$$

88) Verify the above using Python. Note that you might get precision errors (that is, `2.77e-17` instead of `0`).

Why do we do this at all?! For SVD, we seek to _approximate_ large, complex matrices. To see what we mean, let's see what happens when we remove singular values from our matrix.

89) Create a new matrix, $\tilde{S}$, that is the same as $S$, but with _all but the first 20_ singular values turned into zeros. You may call this variable `smat2`.

90) Let's approximate our original `doge` matrix. That is, recombine our decomposed matrix, but this time having removed most of our singular values:

$$\tilde{M} = U\tilde{S}V^T$$

You can call the result `doge_approx`.

91) Visualize `doge_approx` using `plt.imshow()`. How has the image changed?

92) Try this again with values besides 20. Can you still tell what the original image was with only 10 singular values?

### Still... so what?
SVD is at the heart of one sometimes confusing topic - **principal component analysis**. PCA involves carrying out SVD on our data matrix to **reduce its dimensionality**. That is, can we still have all the information we need in a data set while having fewer variables?